### ISSUE TITLE
Adding package to meteor project with release METEOR@1.2.0.2 is impossible

### ISSUE THREAD

**Issue by iguissouma** [lukemadera/meteor-autoform-autocomplete#3]
When adding this package to a project with METEOR@1.2.0.2, I got the folowing errors: 

=> Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint less@1.0.14 is not satisfied by less
2.5.0_3.
Constraints on package "less":
- less@=2.5.0_3 <- top level
- less@1.0.14 <- lukemadera:autoform-autocomplete 1.0.1

Can you publish a new version that fix this problem?
thx in advance.

**Comment by lukemadera** [comment]
Hmm, Meteor 1.2 changed how less works and now the imports are failing. I'll try to take another look this weekend or next week but if you already know how to do this or have a pull request feel free to suggest / direct / fix!

**Comment by iguissouma** [comment]
thanks.
